version: 2

models:
  - name: stg_users
    description: "staging table with demographic information of each user"
    columns:
      - name: user_id
        description: "unique key"
        tests:
          - unique
          - not_null
      - name: user_guid
      - name: address_guid
      - name: first_name
      - name: last_name
      - name: phone_number
      - name: created_at_utc
      - name: updated_at_utc
      - name: email
      - name: email
  
  - name: stg_addresses
    description: "staging table with address information of the users"
    columns:
      - name: address_id
        description: "unique key"
        tests:
          - unique
          - not_null
      - name: address_guid
      - name: address
      - name: zipcode
      - name: state
      - name: country
  
  - name: stg_events
    description: "staging table with event information"
    columns:
      - name: event_id
        description: "unique key"
        tests:
          - unique
          - not_null
      - name: event_guid
      - name: session_guid
      - name: user_guid
      - name: page_url
      - name: created_at_utc
      - name: event_type
  
  - name: stg_orders
    description: "staging table for orders"
    columns:
      - name: order_id
        description: "unique key"
        tests:
          - unique
          - not_null
      - name: order_guid
      - name: user_guid
      - name: promo_guid
      - name: address_guid
      - name: created_at_utc
      - name: order_cost
      - name: shipping_cost
      - name: order_total
      - name: tracking_guid
      - name: shipping_service
      - name: estimated_delivery_at_utc
      - name: delivered_at_utc
      - name: status

  - name: stg_order_items
    description: "staging table for items that have orders"
    columns:
      - name: order_item_id
        description: "unique key"
        tests:
          - unique
          - not_null
      - name: order_guid
      - name: product_guid
      - name: quantity  

  - name: stg_products
    description: "staging table for products"
    columns:
      - name: product_id
        description: "unique key"
        tests:
          - unique
          - not_null
      - name: product_guid
      - name: name
      - name: price
      - name: quantity  

  - name: stg_promos
    description: "staging table for promos"
    columns:
      - name: promo_id
        description: "unique key"
        tests:
          - unique
          - not_null
      - name: promo_guid
      - name: discount
      - name: status

  - name: stg_superheroes
    description: Demographics about each superhero such as name, hair color, height and weight. 
    columns:
      - name: name
        tests:
          - not_null 
      - name: height
        tests:
          - positive_values
      - name: weight
        tests:
          - positive_values
